# Esphome config to connect a Duracell Durai Inverter into homeassistant
# Should also work with similar CYG Skyline based inverters such as the MidNite AIO 
# The register maps where taken from https://github.com/iPeel/HA-Skyline/tree/main
# and my thanks goes out to iPeel who created the above project.
#
# This project requires an ESP32 and a low cost RS232 to RS485 adapter
# 
# A Liligo LILYGO T-CAN485 or a Waveshare ESP32-S3-RS485-CAN should work but may need the UART pins changed
esphome:
  name: durai_inverter
  friendly_name: Durai_Inverter

esp32:
  framework:
    type: esp-idf
  board: esp32dev

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR-KEY"

ota:
  - platform: esphome
    password: "YOUR-PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Durai Fallback Hotspot"
    password: "YOUR_BACKUP-PASSWORD"

captive_portal:

web_server:

logger:
  level: VERBOSE

# UART configuration for RS485
uart:
  id: uart_1
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

# Required for total_daily_energy.
time:
  - platform: sntp

# Configuration for the MODBUS client over UART.
modbus:
  id: mod_bus
  uart_id: uart_1
  role: client

#                inverter_power_data = (0x1001, 64)
#                grid_power_data = (0x1300, 63)
#                battery_data = (0x2000, 19)
#                inverter_config_data = (0x2100, 34)
#                grid_config_data = (0x30B0, 12)
#                eps_data = (0x1350, 19)

modbus_controller:
  - id: skyline
    address: 0x1  # Default slave address for Skyline inverters
    modbus_id: mod_bus
    setup_priority: -10
    update_interval: 10s

sensor:
  # WiFi Signal Strength
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  # System uptime
  - platform: uptime
    name: "Uptime Sensor"

  # Power Sensors (0x1001-0x1040 range)
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Inverter Load L1"
    id: inverter_load_l1
    register_type: holding
    address: 0x1001
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.0001  # Convert to kW (registers are in 0.1W)

  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Inverter Load L2"
    id: inverter_load_l2
    register_type: holding
    address: 0x1006
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.0001

  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Inverter Load L3"
    id: inverter_load_l3
    register_type: holding
    address: 0x100B
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.0001

  # MPPT1 Voltage and Current
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "MPPT1 Voltage"
    id: mppt1_voltage
    register_type: holding
    address: 0x100E
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "MPPT1 Current"
    id: mppt1_current
    register_type: holding
    address: 0x100F
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # MPPT1 Power
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "MPPT1 Power"
    id: mppt1_power
    register_type: holding
    address: 0x1010
    register_count: 2
    response_size: 4
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 3
    value_type: U_DWORD
    filters:
      - multiply: 0.0001

  # MPPT2 Voltage and Current
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "MPPT2 Voltage"
    id: mppt2_voltage
    register_type: holding
    address: 0x1012
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "MPPT2 Current"
    id: mppt2_current
    register_type: holding
    address: 0x1013
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # MPPT2 Power
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "MPPT2 Power"
    id: mppt2_power
    register_type: holding
    address: 0x1014
    register_count: 2
    response_size: 4
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 3
    value_type: U_DWORD
    filters:
      - multiply: 0.0001

  # Total PV Power (template sensor combining MPPT1 and MPPT2)
  - platform: template
    name: "PV Power"
    id: pv_power
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    lambda: |-
      return id(mppt1_power).state + id(mppt2_power).state;

  # System Temperature
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "System Temperature"
    id: system_temp
    register_type: holding
    address: 0x101A
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 0
    value_type: S_WORD

  # PV Energy Today
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "PV Energy Today"
    id: pv_energy_today
    register_type: holding
    address: 0x1025
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    value_type: U_DWORD
    filters:
      - multiply: 0.001

  # PV Energy Total
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "PV Energy Total"
    id: pv_energy_total
    register_type: holding
    address: 0x101F
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    value_type: U_DWORD

  # Grid Power Sensors (0x1300 range)
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Power"
    id: grid_power
    register_type: holding
    address: 0x1300
    register_count: 2
    response_size: 4
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_DWORD
    filters:
      - multiply: 0.0001

  # Grid Energy In Total
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Energy In Total"
    id: grid_energy_in_total
    register_type: holding
    address: 0x1306
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    value_type: U_DWORD
    filters:
      - multiply: 0.01

  # Grid Energy Out Total
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Energy Out Total"
    id: grid_energy_out_total
    register_type: holding
    address: 0x1308
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    value_type: U_DWORD
    filters:
      - multiply: 0.01

  # Grid Tied Load
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Current Load"
    id: grid_tied_load
    register_type: holding
    address: 0x130A
    register_count: 2
    response_size: 4
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_DWORD
    filters:
      - multiply: 0.0001

  # Grid Voltage
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Voltage"
    id: grid_voltage
    register_type: holding
    address: 0x131A
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Grid Current
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Current"
    id: grid_current
    register_type: holding
    address: 0x131D
    register_count: 2
    response_size: 4
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_DWORD
    filters:
      - multiply: 0.01

  # Grid Energy In Today
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Energy In Today"
    id: grid_energy_in_today
    register_type: holding
    address: 0x1332
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    value_type: U_DWORD
    filters:
      - multiply: 0.01

  # Grid Energy Out Today
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Energy Out Today"
    id: grid_energy_out_today
    register_type: holding
    address: 0x1334
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    value_type: U_DWORD
    filters:
      - multiply: 0.01

  # EPS Sensors (0x1350 range)
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "EPS Load L1"
    id: eps_load_l1
    register_type: holding
    address: 0x1353
    register_count: 2
    response_size: 4
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_DWORD
    filters:
      - multiply: 0.0001

  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "EPS Load L2"
    id: eps_load_l2
    register_type: holding
    address: 0x1359
    register_count: 2
    response_size: 4
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_DWORD
    filters:
      - multiply: 0.0001

  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "EPS Load L3"
    id: eps_load_l3
    register_type: holding
    address: 0x135E
    register_count: 2
    response_size: 4
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_DWORD
    filters:
      - multiply: 0.0001

  # Total EPS Load (template sensor)
  - platform: template
    name: "EPS Load"
    id: eps_load
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    lambda: |-
      return id(eps_load_l1).state + id(eps_load_l2).state + id(eps_load_l3).state;

  # Battery Sensors (0x2000 range)
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "State of Charge"
    id: soc
    register_type: holding
    address: 0x2000
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    accuracy_decimals: 0

  # Battery Temperature (currently returns zero according to iPeel)
   - platform: modbus_controller
     modbus_controller_id: skyline
     name: "Battery Temperature"
     id: battery_temp
     register_type: holding
     address: 0x2001
     unit_of_measurement: "°C"
     device_class: temperature
     state_class: measurement
     accuracy_decimals: 0
     value_type: S_WORD

  # Battery Voltage
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Voltage"
    id: battery_voltage
    register_type: holding
    address: 0x2006
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # Battery Current
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Current"
    id: battery_current
    register_type: holding
    address: 0x2007
    register_count: 2
    response_size: 4
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    value_type: S_DWORD
    filters:
      - multiply: 0.01

  # Battery Power
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Load"
    id: battery_load
    register_type: holding
    address: 0x2009
    register_count: 2
    response_size: 4
    unit_of_measurement: "kW"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_DWORD
    filters:
      - multiply: 0.0001

  # Battery Energy In Today
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Energy In Today"
    id: battery_energy_in_today
    register_type: holding
    address: 0x200B
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    value_type: U_DWORD
    filters:
      - multiply: 0.01

  # Battery Energy In Total
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Energy In Total"
    id: battery_energy_in_total
    register_type: holding
    address: 0x200D
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    value_type: U_DWORD
    filters:
      - multiply: 0.01

  # Battery Energy Out Today
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Energy Out Today"
    id: battery_energy_out_today
    register_type: holding
    address: 0x200F
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    value_type: U_DWORD
    filters:
      - multiply: 0.01

  # Battery Energy Out Total
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Energy Out Total"
    id: battery_energy_out_total
    register_type: holding
    address: 0x2011
    register_count: 2
    response_size: 4
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    value_type: U_DWORD
    filters:
      - multiply: 0.01


text_sensor:
  # Device model information (0x1A00 range)
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Model Number"
    id: model_number
    register_type: holding
    address: 0x1A00
    register_count: 8
    response_size: 16
    raw_encode: HEXBYTES

  # Device serial information (0x1A10 range)
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Serial Number"
    id: serial_number
    register_type: holding
    address: 0x1A10
    register_count: 8
    response_size: 16
    raw_encode: HEXBYTES

  # Master software version
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Master Software Version"
    id: master_software_version
    register_type: holding
    address: 0x1A1C
    register_count: 3
    response_size: 6
    raw_encode: HEXBYTES

  # Slave software version
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Slave Software Version"
    id: slave_software_version
    register_type: holding
    address: 0x1A26
    register_count: 3
    response_size: 6
    raw_encode: HEXBYTES

  # EMS software version
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "EMS Software Version"
    id: ems_software_version
    register_type: holding
    address: 0x1A60
    register_count: 3
    response_size: 6
    raw_encode: HEXBYTES

  # DC-DC software version
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "DCDC Software Version"
    id: dcdc_software_version
    register_type: holding
    address: 0x1A6F
    register_count: 3
    response_size: 6
    raw_encode: HEXBYTES

# Binary sensors for grid status
binary_sensor:
  - platform: template
    name: "Grid Importing"
    id: grid_importing
    lambda: |-
      if (id(grid_power).state > 0.1) {
        return true;
      } else {
        return false;
      }

  - platform: template
    name: "Grid Exporting"
    id: grid_exporting
    lambda: |-
      if (id(grid_power).state < -0.1) {
        return true;
      } else {
        return false;
      }

# Switches and numbers for configuration (0x2100 range)
number:
  # Battery Max SoC
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Max SoC"
    id: battery_max_soc
    register_type: holding
    address: 0x2119
    min_value: 10
    max_value: 100
    step: 1

  # Grid Max Charge SoC
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Max Charge SoC"
    id: grid_max_charge_soc
    register_type: holding
    address: 0x2117
    min_value: 10
    max_value: 100
    step: 1

  # Grid Max Charge Power
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Max Charge Power"
    id: grid_max_charge_power
    register_type: holding
    address: 0x2116
    min_value: 0
    max_value: 6000
    step: 50
    unit_of_measurement: "W"

  # Battery Max Charge Power
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Max Charge Power"
    id: battery_max_charge_power
    register_type: holding
    address: 0x2118
    min_value: 0
    max_value: 6000
    step: 50
    unit_of_measurement: "W"

  # Battery Max Power
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Battery Max Power"
    id: battery_max_power
    register_type: holding
    address: 0x211A
    min_value: 0
    max_value: 6000
    step: 50
    unit_of_measurement: "W"

  # Grid Max Feed In Power (0x30B0 range)
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "Grid Max Feed In Power"
    id: grid_max_feed_in_power
    register_type: holding
    address: 0x30BA
    min_value: 0
    max_value: 6000
    step: 50
    unit_of_measurement: "W"

# Select for work mode
#select:
#  - platform: modbus_controller
#    modbus_controller_id: skyline
#    name: "Hybrid Work Mode"
#    id: hybrid_work_mode
#    address: 0x2100
#    optionsmap:
#      "Self Use Mode": 0
#      "Grid-Feed-In-Mode": 1
#      "Time Based Control": 2
#      "Backup Mode": 3

# Switch for EPS Enable
switch:
  - platform: modbus_controller
    modbus_controller_id: skyline
    name: "EPS Enabled"
    id: eps_enabled
    register_type: holding
    address: 0x211C

# Status LED
status_led:
  pin:
    number: GPIO2
